name: TTS
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.1
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - astor=0.8.0
  - attrs=19.3.0
  - audioread=2.1.8
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates
  - certifi=2019.11.28
  - cffi=1.14.0
  - click=7.0
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - ffmpeg=4.0
  - flask=1.1.1
  - fontconfig=2.12.6
  - freetype=2.8
  - gast=0.3.3
  - gettext=0.19.8.1
  - glib=2.63.1
  - gmp=6.1.2
  - google-pasta=0.1.8
  - grpcio=1.14.1
  - gst-plugins-base=1.12.4
  - gstreamer=1.12.4
  - h5py=2.10.0
  - hdf5=1.10.4
  - icu=58.2
  - importlib_metadata=1.5.0
  - inflect=4.1.0
  - intel-openmp=2020.0=166
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - itsdangerous=1.1.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libflac=1.3.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libogg=1.3.2
  - libopus=1.3
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - librosa=0.7.2
  - libsndfile=1.0.28
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libvorbis=1.3.6
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - llvmlite=0.31.0
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=2.1.0
  - mistune=0.8.4
  - mkl
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - ninja=1.9.0
  - notebook=6.0.3
  - numba=0.48.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.0.2u
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2
  - parso=0.6.1
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=5.1.0
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - protobuf=3.11.4
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.5.2
  - pyparsing=2.4.6
  - pyqt=5.6.0
  - pyrsistent=0.15.7
  - pysoundfile=0.10.2
  - python=3.6.6
  - python-dateutil=2.8.1
  - pytorch=1.3.1
  - pytorch-cpu=1.3.1=0
  - pytz=2019.3
  - pyzmq=18.1.1
  - qt=5.6.2
  - readline=7.0
  - resampy=0.2.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=45.2.0
  - sip=4.18.1
  - six=1.14.0
  - sqlite=3.31.1
  - tbb=2020.0
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.3
  - unidecode=1.0.22
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - werkzeug=1.0.0
  - wheel=0.34.2
  - wrapt=1.11.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - vinorm==1.0.0

